default_stages: [commit]
default_language_version:
    python: python3.11
repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: 3.5.3
- hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: forbid-tabs
  - id: remove-tabs
  repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.1
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - args:
    - --unsafe
    id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: isort
  repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
- hooks:
  - id: black
    language_version: python3.11
  repo: https://github.com/ambv/black
  rev: 23.7.0
- hooks:
  - additional_dependencies:
    - flake8-typing-imports==1.12.0
    id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 6.0.0
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
  - id: mypy
    additional_dependencies:
      - types-protobuf
    args:
      - --ignore-missing-imports
      - osm2gpd
      - tests
    pass_filenames: false
    verbose: true
- hooks:
  - args:
    - --in-place
    id: docformatter
  repo: https://github.com/myint/docformatter
  rev: v1.7.5
