name: Publish to PyPI

on:
  workflow_run:
    workflows:
      - Lint
      - Tests
      - MyPy
    branches: [main]
    types:
      - completed

jobs:
  build-n-publish:
    name: Build and publish distribution to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: '1.5.1'
      - name: build
        run: poetry build
      - name: publish
        run: poetry publish --repository=testpypi
        env:
          POETRY_HTTP_BASIC_MY_REPOSITORY_PASSWORD: ${{secrets.PYPI_TOKEN}}
          POETRY_REPOSITORIES_TESTPYPI: https://test.pypi.org/legacy/
